name: Node.js CVE Scanning

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'allow-list.json'
      - 'package.json'
      - 'toolbox/fdc3-workbench/package.json'
      - '.github/workflows/cve-scanning.yml'
      - 'website/package.json'
  # push:
  #   paths:
  #     - 'package.json'
  #     - 'toolbox/fdc3-workbench/package.json'
  #     - '.github/workflows/cve-scanning.yml'
  #     - 'website/package.json'
  schedule:
    # Run every day at 5am and 5pm
    - cron: '0 5,17 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: lnx-build
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm install
      
      - run: npm install
        working-directory: toolbox/fdc3-workbench

      - run: npm install
        working-directory: website

      - run: npx --yes auditjs ossi --whitelist allow-list.json
        if: success() || failure()
        
      - run: npx --yes auditjs ossi --whitelist ../allow-list.json
        working-directory: website
        if: success() || failure()
